spring:
  datasource:
    url: jdbc:mysql://localhost:3306/integrated_aviation_licencing?createDatabaseIfNotExist=true
    username: root
    password: password123
  jpa:
    hibernate:
      ddl-auto: update